# Generated by Django 5.1.1 on 2024-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_number', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_bankrupt', models.BooleanField(default=False)),
                ('is_as', models.BooleanField(default=False)),
            ],
        ),
    ]
