# Generated by Django 5.1.1 on 2024-09-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brreg_api', '0002_company_ansatte_company_forretningsadresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='forretningsadresse',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='frivilligMvaRegistrertBeskrivelser',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='naeringskode1',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='org_form',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='postadresse',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
