# Generated by Django 5.1.1 on 2024-09-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brreg_api', '0005_remove_company_frivilligmvaregistrertbeskrivelser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageResult',
        ),
        migrations.AddField(
            model_name='company',
            name='frivilligMvaRegistrertBeskrivelser',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_as',
            field=models.BooleanField(default=False),
        ),
    ]
