# Generated by Django 5.1.1 on 2024-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brreg_api', '0006_delete_pageresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
